version: '3'

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  app:
    build:
      context: .
    image: cloudolife/col-rust-docker
    # ports:
    #   - "8080:8080"
    # restart: on-failure
    volumes:
      - ".:/Bar_Bot"